version: '3.9'
services:
  nginx:
    restart: always
    container_name: nginx
    image: index.docker.io/starlightromero/stockstalker-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
