version: "3.9"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
